birdy/controllers/favorites.py
import sys
sys.path.append('..')
from birdy.services.ebird_service import EbirdService
from birdy.services.bird import Bird
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from birdy.controllers.auth import login_required
from birdy.db import get_db
from sqlalchemy import text

bp = Blueprint('favorites', __name__, url_prefix='/favorites')

@bp.route('/')
@login_required
def index():
    db = get_db()
    user_id = g.user['id']
    latitude = g.user['latitude']
    longitude = g.user['longitude']
    birds = get_favorite_birds(user_id)
    if birds == []:
        return render_template('favorites/index.html', birds=None)
    else:
        return render_template('favorites/index.html', birds=birds, lat=float(latitude), lng=float(longitude))

@bp.route('/<int:id>', methods=('GET',))
@login_required
def show(id):
    query = text("SELECT * FROM bird WHERE id = :bird_id")
    query = query.bindparams(bird_id=id)
    bird_info = get_db().engine.execute(query).fetchone()
    bird = Bird(bird_info[0], bird_info[2], bird_info[3], str(bird_info[1]))
    sightings = EbirdService().get_nearby_sightings_by_species(g.user['latitude'], g.user['longitude'], bird.species_code)
    return render_template('favorites/show.html', sightings=sightings, bird=bird)

@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    user_id = g.user['id']
    query = text("DELETE FROM user_birds WHERE user_id = :user_id AND bird_id = :bird_id")
    query = query.bindparams(user_id=user_id, bird_id=id)
    get_db().engine.execute(query)
    return redirect(url_for('favorites.index'))

def get_favorite_birds(user_id):
    query = text("SELECT bird_id FROM user_birds WHERE user_id = :user_id")
    query = query.bindparams(user_id=user_id)
    bird_ids = get_db().engine.execute(query).fetchall()

    if bird_ids == []:
        return None
    else:
        birds = []
        for bird_id in bird_ids:
            query = text("SELECT * FROM bird WHERE id = :bird_id")
            query = query.bindparams(bird_id=bird_id[0])
            bird_info = get_db().engine.execute(query).fetchone()
            bird = Bird(bird_info[0], bird_info[2], bird_info[3], bird_info[1])
            birds.append(bird)
        return birds

birdy/templates/favorites/index.html
{% extends 'base.html' %}

{% block header %}
  <h3>{% block title %}Favorite Birds{% endblock %}</h3>
{% endblock %}

{% block content %}
  {% if birds == None %}
    <article class="post">
      <header>
        <div>
          <h3>Go to search to add favorite birds!</h3>
        </div>
      </header>
    </article>
  {% else %}
    {% for bird in birds %}
      <article class="post">
        <header>
          <div>
            <h3>
              <a class="action" href="{{ url_for('favorites.show', id=bird.id) }}">{{ bird.com_name }}</a>
            </h3>
            <div class="about">
              &nbsp;&nbsp;Scientific Name: {{ bird.sci_name }}<br>
              &nbsp;&nbsp;Species Code: <p style="display: inline" class="species-code">{{ bird.species_code }} </p><br>
            </div>
            <form action="{{ url_for('favorites.delete', id=bird.id) }}" method="post">
              <input class="danger" type="submit" value="Remove" onclick="return confirm('Are you sure?');">
            </form>
          </div>
        </header>
      </article>
    {% endfor %}
    <div class="email-sightings">
      <button onclick="emailFavSightings()" id="email-me">Email Nearby Observations</button>
      <button onclick="displaySightings()" id="view-map">View Map of Sightings</button>
    </div>
  {% endif %}

  <div class="favorites-map">
    <div id='map'></div>
  </div>

  <script type="text/javascript">
    $('.favorites-map').hide()

    mapboxgl.accessToken = 'pk.eyJ1IjoiYW1qMTMzIiwiYSI6ImNqaTF6dGZ6cTBhejIza3FzbGhsOHBmZG8ifQ.YRKopJwU0idtffBarsWgaA';

    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v9',
      center: [{{ lng }}, {{ lat }}],
      zoom: 8
    });

    const displaySightings = async () => {
      map.addSource("polygon", createGeoJSONCircle([{{ lng }}, {{ lat }}], 30));
      map.addLayer({
          "id": "polygon",
          "type": "fill",
          "source": "polygon",
          "layout": {},
          "paint": {
              "fill-color": "rgb(90, 180, 200)",
              "fill-opacity": 0.3
          }
      });
      $('.favorites-map').show()
      const rawSightings = await getFavSightings()
      let sightingsGeoJSON = createGeoJSONPoints(rawSightings)
      let i = 0
      sightingsGeoJSON.forEach(function(sightings) {
        map.addLayer({
          "id": "sightings" + i,
          "type": "circle",
          "source": {
            "type": "geojson",
            "data": {
              "type": "FeatureCollection",
              "features": sightings
            }
          },
          "paint": {
            "circle-color": `rgb(${Math.floor(Math.random() * 256)}, ${Math.floor(Math.random() * 256)}, ${Math.floor(Math.random() * 256)})`,
            "circle-radius": 5,
            "circle-stroke-width": 2,
            "circle-stroke-color": "#fff"
          }
        })
        map.on('mouseenter', 'sightings' + i, function () {
            map.getCanvas().style.cursor = 'pointer';
        });
        map.on('mouseleave', 'sightings' + i, function () {
            map.getCanvas().style.cursor = '';
        });
        i += 1
      })
    }

    const getFavSightings = async () => {
      const speciesCodes = getSpeciesCodes()
      const header = {headers: {'X-eBirdApiToken': 'hv9rjmnpb5vo'}}
      const lat = {{ lat }}
      const lng = {{ lng }}
      let sightings = speciesCodes.map(async (speciesCode) => {
        const url = `https://ebird.org/ws2.0/data/obs/geo/recent/${speciesCode}?lat=${lat}&lng=${lng}&distance=25`
        const newSightings = await getBirdSightings(url, header)
        return newSightings
      })
      return Promise.all(sightings)
    }
  </script>
{% endblock %}

birdy/templates/favorites/show.html
{% extends 'base.html' %}

{% block header %}
  <h3>{% block title %}{{ bird.com_name + " (" + bird.sci_name + ")" }}{% endblock %}</h3>
{% endblock %}

{% block content %}
  {% if sightings == None %}
    <article class="post">
      <header>
        <div>
          <h3>No recent observations of this species near your location</h3>
        </div>
      </header>
    </article>
  {% else %}
    {% for sighting in sightings %}
      <article class="post">
        <header>
          <div>
            <h3>{{ sighting.location }}</h3>
            <div class="about">
              Scientific Name: {{ sighting.sci_name }}<br>
              Observation Date: {{ sighting.obs_date }}<br>
              Location: {{ sighting.latitude|string() + ", " + sighting.longitude|string() }}<br>
              How Many: {{ sighting.how_many }}
            </div>
          </div>
        </header>
      </article>
    {% endfor %}
  {% endif %}
{% endblock %}