birdy/controllers/auth.py
import functools
from flask import(
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash
from birdy.db import get_db
from sqlalchemy import text

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        latitude = str(request.form['latitude'])
        longitude = str(request.form['longitude'])
        db = get_db()
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif db.engine.execute(
            text('SELECT id FROM birdy_user WHERE username = :username').bindparams(username=username)
        ).fetchone() is not None:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            query = text("INSERT INTO birdy_user (username, email, notify, password, latitude, longitude) VALUES (:username, :email, :notify, :password, :latitude, :longitude)")
            query = query.bindparams(username=username, email=email, notify='daily', password=generate_password_hash(password), latitude=latitude, longitude=longitude)
            db.engine.execute(query)
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None
        query = text('SELECT * FROM birdy_user WHERE username = :username')
        query = query.bindparams(username=username)
        user = db.engine.execute(query).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        query = text('SELECT * FROM birdy_user WHERE id = :user_id')
        query = query.bindparams(user_id=user_id)
        g.user = get_db().engine.execute(query).fetchone()

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

birdy/controllers/bird_search.py
import sys
sys.path.append('..')
from birdy.services.ebird_service import EbirdService
from birdy.services.bird import Bird
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from birdy.controllers.auth import login_required
from birdy.db import get_db
import ipdb

bp = Blueprint('bird_search', __name__, url_prefix='/search')

@bp.route('/species')
@login_required
def by_species():
    return render_template('search/by_species.html')

@bp.route('/location')
@login_required
def by_location():
    return render_template('search/by_location.html')

birdy/controllers/dashboard.py
import sys
sys.path.append('..')
from birdy.services.ebird_service import EbirdService
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from birdy.controllers.auth import login_required
from birdy.db import get_db
from sqlalchemy import text

bp = Blueprint('dashboard', __name__)

@bp.route('/')
@login_required
def index():
    sightings = EbirdService().get_notable_sightings(g.user['latitude'], g.user['longitude'])
    return render_template('dashboard/index.html', sightings=sightings)

@bp.route('/user/edit', methods=('GET', 'POST'))
@login_required
def edit():
    username = g.user['username']
    if request.method == 'GET':
        email = g.user['email']
        return render_template('dashboard/edit.html', username=username, email=email)
    elif request.method == 'POST':
        new_username = request.form['username']
        new_email = request.form['email']
        new_preference = request.form['notify']
        query = text('UPDATE birdy_user SET username = :new_username, email = :new_email, notify = :notify WHERE username = :old_username')
        query = query.bindparams(new_username=new_username, new_email=new_email, old_username=username, notify=new_preference)
        get_db().engine.execute(query)

    return redirect(url_for('index'))

birdy/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - BirdWatcher</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css' rel='stylesheet'/>

<header class='hero-banner'>
</header>

<nav>
  <div class="bird-logo-container">
    <img src="/static/images/bird4.png" id="bird-logo">
  </div>&nbsp;&nbsp;
  <h1>BirdTracker</h1>
  <ul>
    {% if g.user %}
      <li><span style="color:black;">{{ g.user['username'] }}</span>
      <li class="dropdown">
        <span class="dropbtn">Dashboard</span>
        <div class="dropdown-content">
          <a href="{{ url_for('index') }}">View Sightings</a>
          <a href="{{ url_for('dashboard.edit') }}">Edit Profile</a>
        </div>
      </li>
      <li><a href="{{ url_for('favorites.index') }}">Favorites</a>
      <li class="dropdown">
        <span class="dropbtn">Search</span>
        <div class="dropdown-content">
          <a href="{{ url_for('bird_search.by_location') }}">By Location</a>
          <a href="{{ url_for('bird_search.by_species') }}">By Species Code</a>
        </div>
      </li>
      <li><a href="{{ url_for('auth.logout') }}">Logout</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>

<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}

  {% block content %}{% endblock %}
  <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</section>